# Generated by Django 6.0.3 on 2026-04-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_turmas_escola_professor_carga_maxima_semana_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilidadeprofessor',
            unique_together={('professor', 'dia_semana', 'numero_aula')},
        ),
    ]
