# Generated by Django 6.0.3 on 2026-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplina_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='max_aulas_consecutivas',
            field=models.IntegerField(default=4),
        ),
    ]
