# Generated by Django 6.0.3 on 2026-04-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professor_max_aulas_consecutivas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.escola'),
        ),
        migrations.AddField(
            model_name='professor',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='core.escola'),
        ),
    ]
